### PR TITLE
Add toggle to enable not reporting per keyspace metrics.

### PR DESCRIPTION
**Pull request by jschlather**
This should allow us to turn back on the collectd vitess plugin and not crush our signalfx dpm limits.

### CODE REVIEW

**Comment by makmanalp** [comment]
👍 lgtm

**Comment by acharis** [comment]
i think @PaulFurtado just took care of this at the proxy level

**Comment by jschlather** [comment]
My understanding is that the proxy fix was temporary, because of how long deploys take for us. Going forward we wanted to fix it our end, otherwise we won't be able to add new metrics to the vtgates without changing the proxy and it's pretty unintuitive the way the system works now.

**Comment by acharis** [comment]
ah, got it

**Comment by acharis** [comment]
did you test this somewhere?

**Comment by jschlather** [comment]
No, going to test this in my namespace today.

**Comment by acharis** [comment]
code LGTM ... (not having any context whatsoever)

**Comment by PaulFurtado** [comment]
Yeah, that hack is intended to be temporary so you can deploy the fix at your leisure, but it's weird/oddly specific code so I don't want to keep it around forever.

That said, you can definitely still add new vtgate metrics, it's configured to drop metrics from pods with vtgate in their name that are tagged with a keyspace dimension. So any metrics without a keyspace dimension still come through

**Comment by acharis** [comment]
ah, thx for the context, Paul
and +1 for testing in your namespace, Jacob

**Comment by jschlather** [comment]
Fixed this, but also snuck in a change to support a new timing metric.

**Comment by acharis** [comment]
LGTM

**Pull request merged**
